# lsi: false
# safe: true
# source: .
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge

#theme: jekyll-theme-cayman
remote_theme: yxwzaxns/just-the-docs
plugins:
  - jekyll-remote-theme

repository: copha-project/copha
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false

aux_links:
  "Copha on GitHub":
    - "//github.com/copha-project/copha"

logo: "/assets/images/logo2x1n.png"

search:
  rel_url: false