# lsi: false
# safe: true
# source: .
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge

theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-readme-index
repository: yxwzaxns/copha

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
