# lsi: false
# safe: true
# source: .
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge

#theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme

repository: yxwzaxns/copha
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
