name: Copha build and test

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12]
        os: [ubuntu-latest]
        # node-version: [12, 14, 16]
        # os: [ubuntu-latest, windows-latest, macOS-latest]
    env:
      COPHA_DATA_PATH: /co
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i -g npm
      - run: yarn
      - run: npm run build
      - run: npm run dev -- -h
      - run: mkdir /co
      - run: npm run dev create t1
      - run: npm run dev list
      - run: npm run dev run t1
      - run: npm run dev delete t1